// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlbgfqyfcxsoveflmxsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsYmdmcXlmY3hzb3ZlZmxteHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjA0ODIsImV4cCI6MjA2OTgzNjQ4Mn0.t8EDabSDqh6_No5He5K3tN79Z-Qm9NfXGK2Hfcbmig8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});